version: '3'

services:
  server:
    image: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./php:/var/www/html"
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      app_net:
        ipv4_address: 172.40.2.4

  php:
    build: ./php
    volumes:
      - "./php:/var/www/html"
    networks:
      app_net:
        ipv4_address: 172.40.2.3

  php2:
    container_name: php_server
    build: ./php2
    volumes:
      - "./php:/var/www/html"
    ports:
      - "5000:5000"
    networks:
      app_net:
        ipv4_address: 172.40.2.2

#  sandbox:
#    build: ./sandbox
#    ports:
#      - "3333:3333"

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.40.2.0/24